package gfx

const DEBUG_NONE uint32 = 0
const VIEW_NONE = 0

const DEFAULT_WIDTH = 0
const DEFAULT_HEIGHT = 0

const (
	UINT32_MAX uint32 = 0
	UINT16_MAX uint16 = 0
	UINT64_MAX uint64 = 0
)

const TEXTURE_INTERNAL_DEFAULT_SAMPLER = 0
const TEXTURE_INTERNAL_SHARED = 0


const STATE_DEFAULT = 0
const STATE_NONE    = 0
const STATE_PT_SHIFT = 0

const RESET_INTERNAL_FORCE = 0
const RESET_FLIP_AFTER_RENDER = 0

const (
	STENCIL_DEFAULT = 0
	STENCIL_NONE = 0
	STENCIL_MASK = 0
)

const (
	VIEW_STEREO = 0
)

const (
	SUBMIT_EYE_FIRST = 0
)

const (
	PCI_ID_NONE                uint16 = 0x0000 //!< Autoselect adapter.
	PCI_ID_SOFTWARE_RASTERIZER uint16 = 0x0001 //!< Software rasterizer.
	PCI_ID_AMD                 uint16 = 0x1002 //!< AMD adapter.
	PCI_ID_INTEL               uint16 = 0x8086 //!< Intel adapter.
	PCI_ID_NVIDIA              uint16 = 0x10de //!< nVidia adapter.
)

const BUFFER_INDEX32 = 0
const BUFFER_COMPUTE_WRITE = 0
const BUFFER_ALLOW_RESIZE = 0
const BUFFER_COMPUTE_READ_WRITE = 0
const BUFFER_NONE = 0

const STATE_BLEND_SHIFT = 0
const STATE_ALPHA_REF_SHIFT = 0
const STATE_DEPTH_TEST_SHIFT = 0
const STATE_PT_POINTS = 0
const STATE_POINT_SIZE_SHIFT = 0
const STATE_BLEND_EQUATION_SHIFT = 0

const STATE_MASK = 0

const (
	STATE_CULL_MASK = 0
	STATE_DEPTH_WRITE = 0
	STATE_DEPTH_TEST_MASK = 0
	STATE_RGB_WRITE = 0
	STATE_ALPHA_WRITE = 0
	STATE_BLEND_MASK = 0
	STATE_BLEND_EQUATION_MASK = 0
	STATE_ALPHA_REF_MASK = 0
	STATE_PT_MASK = 0
	STATE_POINT_SIZE_MASK = 0
	STATE_MSAA = 0
	STATE_LINEAA = 0
	STATE_CONSERVATIVE_RASTER = 0
)

const SUBMIT_INTERNAL_OCCLUSION_VISIBLE = 0


const CLEAR_NONE = 0
const CLEAR_DISCARD_MASK = 0
const CLEAR_MASK = 0